name: Java CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Start application in test mode
        run: |
          java -jar artifacts/app-ibank.jar -P:profile=test &
          sleep 5
          echo "Application started in test mode"

      - name: Run tests with headless mode
        run: |
          ./gradlew test --info \
            -Dselenide.headless=true \
            -Dchromeoptions.args="--disable-dev-shm-usage,--no-sandbox,--remote-allow-origins=*,--headless" \
            -Dchromeoptions.prefs="intl.accept_languages=ru"
        timeout-minutes: 10

      - name: Stop application
        run: pkill -f "java -jar artifacts/app-ibank.jar"